const categories = [
  {
    category: "kött, fågel & fisk",
    subcategories: [
      "nötkött",
      "fläskkött",
      "köttfärs",
      "korv",
      "matchark",
      "pålägg",
      "delikatesschark",
      "kyckling & fågel",
      "fisk",
      "skaldjur",
      "sill, kaviar & rom",
      "lamm, kalv & vilt",
    ],
  },
  {
    category: "frukt & grönt",
    subcategories: [
      "frukt",
      "färska bär",
      "grönsaker",
      "potatis & rotfrukter",
      "gourmetgrönsaker",
      "färska kryddor",
      "svamp",
      "lök",
    ],
  },
  {
    category: "mejeri & ost",
    subcategories: [
      "ost",
      "mjölk",
      "mjölkfri dryck",
      "fil & yoghurt",
      "ägg",
      "grädde",
      "smör & margarin",
      "crème fraiche & gräddfil",
      "kvarg & cottage cheese",
      "kylda mellanmål & desserter",
      "juice & fruktdryck",
    ],
  },
  {
    category: "färdigmat",
    subcategories: [
      "portionsrätter",
      "smörgåsar, smörgåstårtor & wraps",
      "gratäng & röror",
      "färska såser",
      "gröt & rullpack",
      "pizzakit & kylda degar",
      "glutenfri färdigmat",
    ],
  },
  {
    category: "barn",
    subcategories: [
      "blöjor",
      "tvättservetter & babyvård",
      "barnmat",
      "barngröt & välling",
      "mellanmål & barndryck",
      "mjölkersättning",
      "babyprylar",
      "barnkalas",
      "leksaker",
    ],
  },
  {
    category: "bröd & kakor",
    subcategories: [
      "bageri",
      "matbröd",
      "kaffebröd",
      "korv- & hamburgerbröd",
      "knäckebröd & skorpor",
      "kex & kakor",
      "riskakor & tilltugg",
      "glutenfritt bröd & kakor",
    ],
  },
  {
    category: "dryck",
    subcategories: [
      "vatten",
      "läsk",
      "stilldrink",
      "sport- & energidryck",
      "öl, cider & must",
      "vin",
      "kaffe, te & choklad",
      "saft & lightdryck",
      "drinkmix & koncentrat",
      "juice & fruktdryck",
    ],
  },
  {
    category: "skafferi",
    subcategories: [
      "all världens mat",
      "kryddor & smaksättare",
      "pasta, ris & mos",
      "fisk & köttkonserver",
      "grönsakskonserver",
      "bönor, linser & fröer",
      "bakning",
      "flingor, müsli & gryner",
      "nötter & torkad frukt",
      "sylt, mos & marmelad",
      "fruktkonserver",
      "desserter",
      "kaffe, te & choklad",
      "påsar & folie",
    ],
  },
  {
    category: "fryst",
    subcategories: [
      "fryst färdigmat",
      "fryst kött & burgare",
      "fryst fågel",
      "fryst fisk & skaldjur",
      "fryst vegetariskt",
      "frysta grönsaker",
      "fryst potatis",
      "fryst frukt & bär",
      "fryst bröd & dessert",
      "färdig is",
      "glass",
    ],
  },
  {
    category: "glass, godis & snacks",
    subcategories: [
      "glass",
      "godis",
      "choklad",
      "chips & snacks",
      "tuggummi",
      "halstabletter",
      "naturgodis & bars",
    ],
  },
  {
    category: "hälsa & skönhet",
    subcategories: [
      "hälsokost",
      "munvård",
      "kroppsvård",
      "hårvård",
      "intimhygien",
      "näsdukar, bomull & tops",
      "smink & nagelvård",
      "hjälpmedel",
    ],
  },
  {
    category: "städ, tvätt & papper",
    subcategories: ["städ", "tvätt", "disk", "toalett- & hushållspapper"],
  },
  {
    category: "kök",
    subcategories: [
      "engångsartiklar",
      "servetter",
      "köksmaskiner",
      "köksredskap",
      "stekpannor, grytor & kastruller",
      "ugnsformar & bakformar",
      "matförvaring",
      "glas & porslin",
      "bestick",
      "kökstextil",
    ],
  },
  {
    category: "hem & inredning",
    subcategories: [
      "inredning",
      "kontor & pyssel",
      "elektronik",
      "böcker, film & spel",
      "kläder, väskor & skor",
    ],
  },
  {
    category: "fritid & trädgård",
    subcategories: ["trädgård", "fritid", "grill", "leksaker & sport"],
  },
  {
    category: "blommor",
    subcategories: ["krukväxter & utplantering"],
  },
  {
    category: "receptfria läkemedel",
    subcategories: [
      "allergi",
      "värk & feber",
      "förkylning",
      "rökfri",
      "övriga receptfria läkemedel",
    ],
  },
];

export default categories;
